<h1>Finding outliers</h1>

step 1: Find Q1 and Q2

step 2: find upperfence and lower fence

```upper fence = q3 + 1.5(iqr)```<br>
```lower fence = q1 + 1.5(iqr)```

```suppose: [1, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 9, 10, 10, 11, 13, 13, 14, 15, 101]```

```uppper fence = 11 - 1.5(7) = 21.5```<br>
```lower fence = 4 -1.5(7) = -6.5```

any number greater than 21.5 is outlier and any number smaller than 6.5 is an outlier

In [63]:
import numpy as np
def finding_outlier(any_list):
    n = len(any_list)
    q1 = np.percentile(any_list, 25)
    q3 = np.percentile(any_list, 75)
    print(q1)
    
    iqr = q3 - q1

    upper_fence = q3 + 1.5 * (iqr)
    lower_fence = q1 - 1.5 * (iqr)
    
    list_of_outliers = []
    for i in any_list:
        if i < lower_fence:
            print(f"outlier found: {i} ")
            list_of_outliers.append(i)
        elif i > upper_fence:
            print(f"outlier found: {i} ")
            list_of_outliers.append(i)
        
        
            
    print(f"\nThe total list of outliers are:\n")
    for i in list_of_outliers:
        print(f"{i}\n")

a = [-7,1, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 9, 10, 10, 11, 13, 13, 14, 15, 101]
print(a)

finding_outlier(a)

[-7, 1, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 9, 10, 10, 11, 13, 13, 14, 15, 101]
4.0
outlier found: -7
outlier found: 101

The total list of outliers are:

-7

101

<h1>Chi test</h1>
<ul>
    <li>Used to check the relationship between two categorical variables.</li>
    <li>
    ML use: Feature selection to identify useful categorical features.</li>
    <li>Example: Checking whether gender is related to purchasing a product.</li>
    
</ul>

In [78]:
import seaborn as sns
import pandas as pd

from scipy.stats import chi2_contingency

In [80]:
df= sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [83]:
contingency_table = pd.crosstab(df['sex'], df['survived'])
contingency_table

survived    0    1
sex
female     81  233
male      468  109

In [84]:
chi2, p_value, dof, expected = chi2_contingency(contingency_table )

In [85]:
chi2

np.float64(260.71702016732104)

In [86]:
p_value

np.float64(1.1973570627755645e-58)

In [ ]:
dof

In [ ]:
expected

In [88]:
alpha = 0.05

In [89]:
if p_value < alpha:
    print("there is significant relationship between gender and survived ")
else:
    print("there is no significant relationship")

there is significant relationship between gender and survived

#  Z-Test
- **Purpose:** Compares a sample mean or proportion with a population value, or compares two proportions, when assumptions are met.
- **ML use:** Testing whether a conversion rate differs significantly from a baseline.
- **Example:** Comparing conversion rates of two website designs.

In [90]:
from scipy.stats import norm
# population std and mean should be given. if not use t-testa
# the sample size should be greater than 30(here we use sample size of less than 30 just for ease)

In [94]:
sample = [172, 174, 168, 169, 171, 173, 175, 170, 169, 172]
population_mean = 170
population_std = 3
sample_mean = np.mean(sample)
n = len(sample)

In [95]:
z_score = (sample_mean - population_mean) / (population_std/ np.sqrt(n))
z_score

np.float64(1.3703203194063098)

In [100]:
p_value = 2 * (1 - norm.cdf(abs(z_score)))
p_value

np.float64(0.17058693287143756)

In [99]:
alpha = 0.05
if p_value<alpha:
    print("reject the null hypothesis")
else:
    print("accept the null hypothesis")

accept the null hypothesis

#  One-Sample T-Test
- **Purpose:** Compares a sample mean with a known or hypothesized value.
- **ML use:** Checking whether the average prediction error differs from a target value.
- **Example:** Testing whether the average error differs from 5.

In [101]:
from scipy import stats

In [103]:
sample = [172, 174, 168, 169, 171, 173, 175, 170, 169, 172]
sample_mean = np.mean(sample)
sample_std = np.std(sample, ddof= 1)
n = len(sample)
mean_population = 170

In [105]:
t_stats= (sample_mean- mean_population)/(sample_std/np.sqrt(n))
t_stats

np.float64(1.7782469350914734)

In [108]:
p_value = 2 * (1 -stats.t.cdf(abs(t_stats), df= n -1))
alpha = 0.05
p_value

np.float64(0.10907771593031335)

In [ ]:
if p_value < alpha:
    print("rejec null hypo")
else:
    print("accept null")

# 4. Two-Sample T-Test
- **Purpose:** Compares the means of two independent groups.
- **ML use:** Comparing the performance of two models or two groups.
- **Example:** Checking whether Model A and Model B have significantly different average errors

In [112]:
group_A = [85, 88, 90, 92 , 87, 85, 91, 86, 88 ]
group_b = [82, 84,80,83,81,79,78,85,84,83]

In [113]:
t_stats, p_value = stats.ttest_ind(group_A, group_b, equal_var=False)

In [114]:
t_stats

np.float64(5.422370986155527)

In [115]:
alpha = 0.05
if p_value < alpha:
    print("reject null hypo")
else:
    print("accept the null hypo")

reject null hypo

#  ANOVA (Analysis of Variance)
- **Purpose:** Compares the means of three or more groups.
- **ML use:** Comparing the performance of multiple models or different configurations.
- **Example:** Comparing the accuracy scores of three machine learning algorithms.

In [127]:
from scipy.stats import f_oneway

In [134]:
df = sns.load_dataset('titanic')
df= df[['age', 'pclass']].dropna()

In [135]:
class_1 = df[df['pclass'] == 1]['age']
class_2 = df[df['pclass'] == 2]['age']
class_3 = df[df['pclass'] == 3]['age']

In [136]:
f_stats, p_value = f_oneway(class_1, class_2, class_3)

In [137]:
f_stats

np.float64(57.443484340676214)

In [138]:
p_value

np.float64(7.487984171957457e-24)

In [ ]:
alpha = 0.05
if p_value < alpha:
    print('there is significant diff in atleast one passenger class')
else:
    print('there is no significant diff in atleast one passenger class')

# Covariance

- **Purpose:** Measures how two numerical variables change together.
- **Positive covariance:** Both variables tend to increase or decrease together.
- **Negative covariance:** When one variable increases, the other tends to decrease.
- **Zero covariance:** No linear co-movement is indicated.
- **ML use:** Understanding relationships between features and identifying patterns in data.
- **Example:** Studying how hours studied and exam scores change together.
- **Remember:** Covariance shows the direction of a relationship, while correlation measures its strength and direction on a scale from -1 to +1.

#  Correlation

- **Purpose:** Measures the strength and direction of the relationship between two numerical variables.
- **Positive correlation:** When one variable increases, the other tends to increase.
- **Negative correlation:** When one variable increases, the other tends to decrease.
- **Zero correlation:** No linear relationship between the variables.
- **ML use:** Understanding relationships between features and identifying patterns in data.
- **Example:** Studying the relationship between hours studied and exam scores.
- **Correlation coefficient:** Ranges from -1 to +1.
  - **+1:** Perfect positive correlation.
  - **-1:** Perfect negative correlation.